// select all buttons 
const leftBracket = document.querySelector("#leftBracket"); 
const rightBracket = document.querySelector("#rightBracket"); 
const mod = document.querySelector("#mod"); 
const AC = document.querySelector("#AC"); 
const seven = document.querySelectorAll("#seven"); 
const eight = document.querySelector("#eight"); 
const nine = document.querySelector("#nine"); 
const div = document.querySelector("#div"); 
const four = document.querySelector("#four"); 
const five = document.querySelector("#five"); 
const six = document.querySelector("#six"); 
const mult = document.querySelector("#seven"); 
const one = document.querySelector("#one"); 
const two = document.querySelector("#two"); 
const three = document.querySelector("#three"); 
const minus = document.querySelector("#minus"); 
const zero = document.querySelector("#zero"); 
const dot = document.querySelector("#dot"); 
const equal = document.querySelector("#equal"); 
const plus = document.querySelector("#plus"); 

